### PR TITLE
Vendor dependencies using dep

### PR DESCRIPTION
**Pull request by plorefice**
This is a huge QoL improvement for new contributors who do not have to manually install all the required dependencies when checking out the repo. Plus it freezes the dependency versions, avoiding breaking changes.

PS: I also added to `.gitignore` the default executable name on Linux/macOS.

### CODE REVIEW

**Comment by Bunchhieng** [comment]
Thanks for the PR. Please ignore `vendor` folder in gitignore.

**Comment by plorefice** [comment]
Actually, the common practice is to *not* ignore the `vendor` folder,
because newer Go versions will look in it first, then in GOPATH for
dependencies. This way, you can clone and build without additional steps,
and have all the dependencies in sync :)

As for the CI errors, I already have a PR ready that fixes those, when this
will be merged.

**Comment by Bunchhieng** [comment]
Sounds good. Thanks for adding the vendor folder. Could you please fix the build failure?

**Review by Bunchhieng — CHANGES_REQUESTED** [review]
Please fix the build failure.

**Comment by plorefice** [comment]
I pushed an update to the `.travis.yml` which:

- updates Go to version 1.11 (I recommend always using the latest stable)
- removes dependency fetching, since now everything is vendored

This fixes the CI and build issues :)

**Comment by Bunchhieng** [comment]
Wonderful! Thanks for working on this. 👍

**Review by Bunchhieng — APPROVED** [review]

**Pull request merged**
